services:
  chatapp-api:
    image: ${DOCKERHUB_USERNAME:-grandprix1999}/chatapp-api:${CHATAPP_API_TAG:-latest}
    ports:
      - "5002:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - chatapp-network

  chatapp-frontend:
    image: ${DOCKERHUB_USERNAME:-grandprix1999}/chatapp-frontend:${CHATAPP_FRONTEND_TAG:-latest}
    ports:
      - "7862:80"
    depends_on:
      - chatapp-api
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge
